/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ColorSignal = IDL.Variant({
  'red' : IDL.Null,
  'green' : IDL.Null,
  'violet' : IDL.Null,
});
export const Time = IDL.Int;
export const Prediction = IDL.Record({
  'result' : IDL.Bool,
  'colorSignal' : ColorSignal,
  'inputNumber' : IDL.Nat8,
  'timestamp' : Time,
  'luckyNumbers' : IDL.Vec(IDL.Nat8),
});

export const idlService = IDL.Service({
  'getLast20Records' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
  'submitPrediction' : IDL.Func([IDL.Nat8], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ColorSignal = IDL.Variant({
    'red' : IDL.Null,
    'green' : IDL.Null,
    'violet' : IDL.Null,
  });
  const Time = IDL.Int;
  const Prediction = IDL.Record({
    'result' : IDL.Bool,
    'colorSignal' : ColorSignal,
    'inputNumber' : IDL.Nat8,
    'timestamp' : Time,
    'luckyNumbers' : IDL.Vec(IDL.Nat8),
  });
  
  return IDL.Service({
    'getLast20Records' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
    'submitPrediction' : IDL.Func([IDL.Nat8], [], []),
  });
};

export const init = ({ IDL }) => { return []; };